@componentsRoot: src/pages

home:
  url: /home
  component: home.component#HomeComponent
products:
  url: /products
  component: products.component#ProductsComponent
product:
  url: /product/:id
  component: product.component#ProductComponent
  .about:
    url: /about # /product/:id/about
    component: product/about.component#ProductAboutComponent
  .comments:
    url: /comments # /product/:id/comments
    dynamic: true
    component: product/comments.component#ProductCommentsComponent
    .all:
      url: / 
      component: product/comments-all.component#ProductCommentsAllComponent
    .best:
      url: /best # /product/:id/comments/best
      component: product/comments-best.component # if component exported as deafult (why not?)
    .filter:
      url: /filter?page&author&from&to&query
      component: product/comments/filter-comments.component
      params:
        page: int
        author: string
        from: date
        to: date
        query: string
# Or
  @dynamic .comments: # @dynamic is a directive, equals to `dynamic: true`
    .: /comments => product/comments.component#ProductCommentsComponent
    .all: / => product/comments.component#ProductCommentsAllComponent
    .best: /best => product/comments-best.component#ProductCommentsBestComponent
